project:
  type: website
  output-dir: docs
lang: fr
website:
  title: "Titre du cours"
  navbar:
    left:
      - href: index.qmd
        text: Commencer
      - href: page1.qmd
        text: Ressources
      - href: about.qmd
        text: À propos du cours
  back-to-top-navigation: true
format:
  html:
    theme: cosmo
    css: styles.css
    embed-resources: true
    toc: true
