project:
  type: website

website:
  title: "Ressources SSD"
  navbar:
    left:
      - href: index.qmd
        text: Accueil
      - href: templates.qmd
        text: Modèles
      - href: outils.qmd
        text: Outils
      - href: tutoriels.qmd
        text: Tutoriels
      - href: about.qmd
        text: À propos
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

