project:
  type: website
  output-dir: docs

website:
  title: ""  # On cache le titre textuel
  navbar:
    logo: img/logo-ulaval.png
    tools:
      - icon: github
        href: https://github.com/AurelienNicosiaULaval/site_ressources_SSD
        aria-label: GitHub
      - toggle-appearance: true
    left:
      - href: index.qmd
        text: Accueil
      - href: templates.qmd
        text: Modèles
      - href: outils.qmd
        text: Outils
      - href: tutoriels.qmd
        text: Tutoriels
      - href: about.qmd
        text: À propos


format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual
